Improve error message for getMock's invalid $methods argument
Now gives better error message:
```
There was 1 error:

1) ExampleTest::testExample
PHPUnit_Framework_Exception: Argument #2 (string#__construct)of PHPUnit_Framework_MockObject_Generator::getMock() must be a array

/<path>/ExampleTest.php:8
```

Instead of:
```
There was 1 error:

1) ExampleTest::testExample
InvalidArgumentException: 

/<path>/ExampleTest.php:8
```