Added deafult value for TestCase::runTestInSeparateProcess
Currently there is no default value for the non-nullable boolean member property `TestCase::runTestInSeparateProcess` and it is also not set in the constructor. This causes a psalm issue (see https://psalm.dev/074):

```
ERROR: PropertyNotSetInConstructor - tests/unit/Foo/Bar/BazTest.php:12:34 - Property Foo\Bar\BazTest::$runTestInSeparateProcess is not defined in constructor of Foo\Bar\BazTest and in any methods called in the constructor (see https://psalm.dev/074)
final class BazTest extends TestCase
```

To solve this, I have added a default value (false) to that property.